# Test Case to Patch Mapping Configuration
# Format: test_name:patch_file
# Lines starting with # are comments

test_selinux_relabel_for_existing_pvc:selinux-relabel-test-rename.patch
# Node failure test patch
test_check_pods_status_after_node_failure:test_check_pods_status_after_node_failure.patch

# Node restart test patch
test_nodes_restart:test_nodes-restart.patch
