CURRENT_OCS_CHANNEL=4.15
UPGRADE_OCS_IMAGE=quay.io/rhceph-dev/ocs-registry:latest-stable-4.16
UPGRADE_OCS_CHANNEL=4.16
OCP_VERSION=4.16

PLATFORM=powervm
VAULT_SUPPORT=false
FIPS_ENABLEMENT=false

# Auth YAML as a single-line string
AUTH_YAML=""
MUST_GATHER_IMAGE="quay.io/rhceph-dev/ocs-must-gather:latest-4.19"
#"quay.io/rhceph-dev/odf4-odf-must-gather-rhel9:v4.21.0"

